// Generated by plimsoll-specgen from "Smart Home Control" v1.2.0. Do not edit by hand.
;(function () {
  const h = globalThis["home"];
  if (!h) return;
  h["listLights"] = () => h.get("/lights");
  h["createLight"] = (body) => h.post("/lights", body);
  h["getLight"] = (id) => h.get("/lights/" + id);
  h["setLight"] = (id, body) => h.put("/lights/" + id, body);
  h["deleteLight"] = (id) => h.del("/lights/" + id);
  h["updateLight"] = (id, body) => h.patch("/lights/" + id, body);
  h["listRoomLights"] = (room) => h.get("/rooms/" + room + "/lights");
  h["listScenes"] = () => h.get("/scenes");
  h["getStatus"] = () => h.get("/status");
})();
